#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ANsyn_reg(void);
extern void _bgka_reg(void);
extern void _burststim2_reg(void);
extern void _cad_reg(void);
extern void _cagk_reg(void);
extern void _calH_reg(void);
extern void _cal_reg(void);
extern void _car_reg(void);
extern void _cat_reg(void);
extern void _ccanl_reg(void);
extern void _gskch_reg(void);
extern void _hha2_reg(void);
extern void _hha_old_reg(void);
extern void _h_reg(void);
extern void _hNa_reg(void);
extern void _IA_reg(void);
extern void _ichan2_reg(void);
extern void _Ih_reg(void);
extern void _kad_reg(void);
extern void _kap_reg(void);
extern void _Kaxon_reg(void);
extern void _kca_reg(void);
extern void _Kdend_reg(void);
extern void _km_reg(void);
extern void _Ksoma_reg(void);
extern void _LcaMig_reg(void);
extern void _my_exp2syn_reg(void);
extern void _Naaxon_reg(void);
extern void _Nadend_reg(void);
extern void _Nasoma_reg(void);
extern void _nca_reg(void);
extern void _nmda_reg(void);
extern void _regn_stim_reg(void);
extern void _somacar_reg(void);
extern void _STDPE2Syn_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," mod//ANsyn.mod");
    fprintf(stderr," mod//bgka.mod");
    fprintf(stderr," mod//burststim2.mod");
    fprintf(stderr," mod//cad.mod");
    fprintf(stderr," mod//cagk.mod");
    fprintf(stderr," mod//calH.mod");
    fprintf(stderr," mod//cal.mod");
    fprintf(stderr," mod//car.mod");
    fprintf(stderr," mod//cat.mod");
    fprintf(stderr," mod//ccanl.mod");
    fprintf(stderr," mod//gskch.mod");
    fprintf(stderr," mod//hha2.mod");
    fprintf(stderr," mod//hha_old.mod");
    fprintf(stderr," mod//h.mod");
    fprintf(stderr," mod//hNa.mod");
    fprintf(stderr," mod//IA.mod");
    fprintf(stderr," mod//ichan2.mod");
    fprintf(stderr," mod//Ih.mod");
    fprintf(stderr," mod//kad.mod");
    fprintf(stderr," mod//kap.mod");
    fprintf(stderr," mod//Kaxon.mod");
    fprintf(stderr," mod//kca.mod");
    fprintf(stderr," mod//Kdend.mod");
    fprintf(stderr," mod//km.mod");
    fprintf(stderr," mod//Ksoma.mod");
    fprintf(stderr," mod//LcaMig.mod");
    fprintf(stderr," mod//my_exp2syn.mod");
    fprintf(stderr," mod//Naaxon.mod");
    fprintf(stderr," mod//Nadend.mod");
    fprintf(stderr," mod//Nasoma.mod");
    fprintf(stderr," mod//nca.mod");
    fprintf(stderr," mod//nmda.mod");
    fprintf(stderr," mod//regn_stim.mod");
    fprintf(stderr," mod//somacar.mod");
    fprintf(stderr," mod//STDPE2Syn.mod");
    fprintf(stderr," mod//vecevent.mod");
    fprintf(stderr, "\n");
  }
  _ANsyn_reg();
  _bgka_reg();
  _burststim2_reg();
  _cad_reg();
  _cagk_reg();
  _calH_reg();
  _cal_reg();
  _car_reg();
  _cat_reg();
  _ccanl_reg();
  _gskch_reg();
  _hha2_reg();
  _hha_old_reg();
  _h_reg();
  _hNa_reg();
  _IA_reg();
  _ichan2_reg();
  _Ih_reg();
  _kad_reg();
  _kap_reg();
  _Kaxon_reg();
  _kca_reg();
  _Kdend_reg();
  _km_reg();
  _Ksoma_reg();
  _LcaMig_reg();
  _my_exp2syn_reg();
  _Naaxon_reg();
  _Nadend_reg();
  _Nasoma_reg();
  _nca_reg();
  _nmda_reg();
  _regn_stim_reg();
  _somacar_reg();
  _STDPE2Syn_reg();
  _vecevent_reg();
}
